// SPDX-FileCopyrightText: 2026 Unity Technologies and the glTFast authors
// SPDX-License-Identifier: Apache-2.0

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
#if UNITY_6000_6_OR_NEWER
using UnityEngine.Assemblies;
#endif
using UnityEngine.Scripting.APIUpdating;

namespace Unity.Cloud.Gltfast.Editor.Tests
{
    /// <summary>
    /// Guards the API Updater input for the 7.0 rename: every public type in the renamed shipping
    /// assemblies either carries a correct [MovedFrom] or is classified as introduced after the rename.
    /// </summary>
    [TestFixture]
    class MovedFromAttributeCoverageTests
    {
        // New assembly name -> pre-7.0 (glTFast 6.x) assembly name.
        static readonly (string newAssembly, string oldAssembly)[] k_ShippingAssemblies =
        {
            ("Unity.Cloud.Gltfast", "glTFast"),
            ("Unity.Cloud.Gltfast.Export", "glTFast.Export"),
            ("Unity.Cloud.Gltfast.Newtonsoft", "glTFast.Newtonsoft"),
            ("Unity.Cloud.Gltfast.Dots", "glTFast.dots"),
            ("Unity.Cloud.Gltfast.Editor", "glTFast.Editor"),
        };

        const string k_NewRootNamespace = "Unity.Cloud.Gltfast";
        const string k_OldRootNamespace = "GLTFast";

        // Namespaces whose last segment was renamed in 7.0 too, so swapping the root prefix does not
        // yield the 6.x name. New namespace -> pre-7.0 (glTFast 6.x) namespace.
        static readonly Dictionary<string, string> k_RenamedNamespaces = new(StringComparer.Ordinal)
        {
            [k_NewRootNamespace + ".Objects"] = k_OldRootNamespace + ".Schema",
        };

        // Union of origin/develop's default, -entities and -HDRP projects, generated by
        // Tools/scripts/GeneratePreRenameTypes.cs; never hand-edited.
        const string k_PreRenameTypesAsset =
            "Packages/com.unity.cloud.gltfast.tests/Tests/Editor/ApiUpdater/PreRenameTypes.txt";

        const string k_UpgradeGuideAsset =
            "Packages/com.unity.cloud.gltfast/Documentation~/UpgradeGuides.md";

        const string k_RenamedTableHeading = "Types that were renamed as well as moved";

        // Keys are reflected 6.x names — declared on the *Base types, while UpgradeGuides.md names the
        // derived type a consumer writes in source; values are the 7.0 types they resolve to.
        static readonly Dictionary<string, string> k_RenamedAndMoved = new(StringComparer.Ordinal)
        {
            ["GLTFast.Schema.GltfAccessorAttributeType"] = "Unity.Cloud.Gltfast.Objects.AccessorType",
            ["GLTFast.Schema.GltfComponentType"] = "Unity.Cloud.Gltfast.Objects.AccessorDataType",
            ["GLTFast.Schema.DrawMode"] = "Unity.Cloud.Gltfast.Objects.PrimitiveMode",
            ["GLTFast.Schema.InterpolationType"] = "Unity.Cloud.Gltfast.Objects.Interpolation",
            ["GLTFast.Schema.CameraBase+Type"] = "Unity.Cloud.Gltfast.Objects.CameraType",
            ["GLTFast.Schema.LightPunctual+Type"] = "Unity.Cloud.Gltfast.Objects.LightType",
#if UNITY_ANIMATION || GLTFAST_ANIMATION
            ["GLTFast.Schema.AnimationChannelBase+Path"] = "Unity.Cloud.Gltfast.Objects.AnimationPath",
#endif
            ["GLTFast.Schema.MeshGpuInstancing+Attributes"] = "Unity.Cloud.Gltfast.Objects.InstancesAttributes",
            ["GLTFast.Schema.MaterialBase+AlphaMode"] = "Unity.Cloud.Gltfast.Objects.AlphaMode",
            ["GLTFast.Schema.Sampler+MagFilterMode"] = "Unity.Cloud.Gltfast.Objects.MagFilterMode",
            ["GLTFast.Schema.Sampler+MinFilterMode"] = "Unity.Cloud.Gltfast.Objects.MinFilterMode",
            ["GLTFast.Schema.Sampler+WrapMode"] = "Unity.Cloud.Gltfast.Objects.WrapMode",
        };

        static HashSet<string> s_PreRenameTypes;

        static HashSet<string> PreRenameTypes
        {
            get
            {
                if (s_PreRenameTypes == null)
                {
                    var asset = AssetDatabase.LoadAssetAtPath<TextAsset>(k_PreRenameTypesAsset);
                    Assert.IsNotNull(asset, $"{k_PreRenameTypesAsset} is missing.");
                    s_PreRenameTypes = new HashSet<string>(
                        asset.text.Split('\n').Select(line => line.Trim()).Where(line => line.Length > 0),
                        StringComparer.Ordinal);
                }

                return s_PreRenameTypes;
            }
        }

        static IEnumerable<(Type type, string newAssembly, string oldAssembly)> PackageTypes()
        {
            foreach (var (newAssembly, oldAssembly) in k_ShippingAssemblies)
            {
                var assembly = FindLoadedAssembly(newAssembly);
                if (assembly == null)
                {
                    // Assembly absent from this configuration (e.g. optional dependency's define off).
                    // The core assembly must always be present; missing optional ones are skipped.
                    continue;
                }

                foreach (var type in assembly.GetExportedTypes())
                {
                    if (type.IsNested)
                        continue; // nested public types migrate with their [MovedFrom]-annotated parent
                    // Other packages' source generators inject types into this assembly.
                    if (!BelongsToPackage(type))
                        continue;
                    yield return (type, newAssembly, oldAssembly);
                }
            }
        }

        static IEnumerable<TestCaseData> PublicShippingTypes()
        {
            foreach (var (type, newAssembly, oldAssembly) in PackageTypes())
            {
                yield return new TestCaseData(type, oldAssembly)
                    .SetName($"{newAssembly}::{type.FullName}");
            }
        }

        [Test]
        public void CoreAssemblyIsLoaded()
        {
            Assert.IsNotNull(FindLoadedAssembly(k_NewRootNamespace),
                $"The renamed core assembly '{k_NewRootNamespace}' is not loaded; " +
                "the coverage test cannot run.");
        }

        [TestCaseSource(nameof(PublicShippingTypes))]
        public void PublicTypeIsClassified(Type type, string expectedOldAssembly)
        {
            var attribute = type.GetCustomAttribute<MovedFromAttribute>();
            var oldFullName = $"{ExpectedOldNamespace(type)}.{type.Name}";
            var existedBeforeRename = PreRenameTypes.Contains(oldFullName);

            if (attribute == null)
            {
                Assert.IsFalse(existedBeforeRename,
                    $"Public type {type.FullName} carries no [MovedFrom], but glTFast 6.x exported " +
                    $"{oldFullName}, so upgrading consumer code breaks. Add:\n" +
                    $"    [MovedFrom(true, sourceNamespace: \"{ExpectedOldNamespace(type)}\", " +
                    $"sourceAssembly: \"{expectedOldAssembly}\")]");
                return;
            }

            var source = ReadSource(attribute);
            // Asserted before oldFullName is used: that name derives from type.Name, so a sourceClassName
            // would make every message below name the wrong type. The updater throws on a rename combined
            // with an assembly move and abandons the whole run, so one such attribute stops every other
            // type from migrating too.
            Assert.IsNull(source.className,
                $"{type.FullName}: [MovedFrom] cannot set sourceClassName on a type that also moves to " +
                $"another assembly ({source.assembly} -> {type.Assembly.GetName().Name}). Doing so aborts " +
                "the API Updater for the entire assembly.");

            Assert.IsTrue(existedBeforeRename,
                $"Public type {type.FullName} carries [MovedFrom], but glTFast 6.x exported no " +
                $"{oldFullName}. Drop the attribute, or regenerate {k_PreRenameTypesAsset}.");

            var expectedOldNamespace = ExpectedOldNamespace(type);
            Assert.AreEqual(expectedOldNamespace, source.nameSpace,
                $"{type.FullName}: [MovedFrom] sourceNamespace should be \"{expectedOldNamespace}\".");
            Assert.AreEqual(expectedOldAssembly, source.assembly,
                $"{type.FullName}: [MovedFrom] sourceAssembly should be \"{expectedOldAssembly}\".");
        }

        [Test]
        public void RenamedTypesResolve()
        {
            var assembly = FindLoadedAssembly(k_NewRootNamespace);
            Assert.IsNotNull(assembly, $"The renamed core assembly '{k_NewRootNamespace}' is not loaded.");

            foreach (var pair in k_RenamedAndMoved)
            {
                Assert.IsTrue(PreRenameTypes.Contains(pair.Key),
                    $"k_RenamedAndMoved names \"{pair.Key}\", which glTFast 6.x did not export. " +
                    $"Drop the entry, or regenerate {k_PreRenameTypesAsset}.");

                var renamed = assembly.GetType(pair.Value, throwOnError: false);
                Assert.IsNotNull(renamed,
                    $"k_RenamedAndMoved maps \"{pair.Key}\" to \"{pair.Value}\", which no longer exists. " +
                    "Update the entry and the table it mirrors in UpgradeGuides.md.");
                Assert.IsTrue(renamed.IsPublic,
                    $"\"{pair.Value}\" is not public, so a consumer cannot migrate to it. " +
                    "Update the entry and the table it mirrors in UpgradeGuides.md.");
            }
        }

        [Test]
        public void UpgradeGuideDocumentsEveryRenamedType()
        {
            var documented = DocumentedRenames();
            var mapped = k_RenamedAndMoved.Values
                .Select(name => name.Substring(name.LastIndexOf('.') + 1))
                .ToList();

            CollectionAssert.IsSubsetOf(mapped, documented,
                $"k_RenamedAndMoved maps to types the \"{k_RenamedTableHeading}\" table in " +
                $"{k_UpgradeGuideAsset} does not list, so a consumer following the guide never learns " +
                "to rename them.");

            // Only the reverse direction needs every entry compiled: an entry behind an #if is absent
            // from the dictionary in a configuration lacking its module, while the guide lists it always.
#if UNITY_ANIMATION || GLTFAST_ANIMATION
            CollectionAssert.IsSubsetOf(documented, mapped,
                $"The \"{k_RenamedTableHeading}\" table in {k_UpgradeGuideAsset} lists types " +
                "k_RenamedAndMoved does not map, so nothing verifies they resolve.");
#endif
        }

        static List<string> DocumentedRenames()
        {
            var path = Path.GetFullPath(k_UpgradeGuideAsset);
            Assert.IsTrue(File.Exists(path), $"{k_UpgradeGuideAsset} is missing.");

            var names = new List<string>();
            var inSection = false;
            var row = 0;
            foreach (var line in File.ReadAllLines(path))
            {
                if (line.StartsWith("#", StringComparison.Ordinal))
                {
                    if (inSection)
                        break;
                    inSection = line.Contains(k_RenamedTableHeading);
                }
                else if (inSection && line.StartsWith("|", StringComparison.Ordinal))
                {
                    var cells = line.Split('|');
                    if (cells.Length < 3)
                        continue;
                    // The header cell is otherwise indistinguishable from a type name; the separator
                    // filter is kept too, so a second table under this heading cannot inject one.
                    if (row++ < 2)
                        continue;
                    var to = cells[2].Trim().Trim('`');
                    if (to.Length > 0 && to.Trim('-', ':', ' ').Length > 0)
                        names.Add(to);
                }
            }

            Assert.IsNotEmpty(names,
                $"Found no \"{k_RenamedTableHeading}\" table in {k_UpgradeGuideAsset}; " +
                "the heading or the table shape changed.");
            return names;
        }

        [Test]
        public void NoTwoTypesClaimTheSameOldName()
        {
            var claims = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var (type, _, _) in PackageTypes())
            {
                var attribute = type.GetCustomAttribute<MovedFromAttribute>();
                if (attribute == null)
                    continue;

                var source = ReadSource(attribute);
                var claim = $"{source.assembly}::{source.nameSpace}.{source.className ?? type.Name}";
                if (claims.TryGetValue(claim, out var other))
                {
                    Assert.Fail($"{type.FullName} and {other} both claim the pre-rename name \"{claim}\"; " +
                        "the API Updater cannot rewrite one old name to two types.");
                }

                claims[claim] = type.FullName;
            }
        }

        static Assembly FindLoadedAssembly(string name)
        {
#if UNITY_6000_6_OR_NEWER
            return CurrentAssemblies.GetLoadedAssemblies()
#else
            return AppDomain.CurrentDomain.GetAssemblies()
#endif
                .FirstOrDefault(a => a.GetName().Name == name);
        }

        // A type belongs to glTFast's public API if it lives under the package's root namespace.
        // Types a source generator injects into the assembly (Entities, Burst, …) sit in their own
        // namespaces, so this cleanly excludes them without hard-coding individual type names.
        static bool BelongsToPackage(Type type)
        {
            var ns = type.Namespace;
            return ns != null
                && (ns == k_NewRootNamespace
                    || ns.StartsWith(k_NewRootNamespace + ".", StringComparison.Ordinal));
        }

        static string ExpectedOldNamespace(Type type)
        {
            var ns = type.Namespace ?? string.Empty;
            if (k_RenamedNamespaces.TryGetValue(ns, out var renamed))
                return renamed;
            if (ns == k_NewRootNamespace)
                return k_OldRootNamespace;
            if (ns.StartsWith(k_NewRootNamespace + ".", StringComparison.Ordinal))
                return k_OldRootNamespace + ns.Substring(k_NewRootNamespace.Length);
            return ns;
        }

        static (string nameSpace, string assembly, string className) ReadSource(MovedFromAttribute attribute)
        {
            const BindingFlags flags = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;
            var data = typeof(MovedFromAttribute).GetField("data", flags)?.GetValue(attribute);
            if (data == null)
                throw new InvalidOperationException("ReadSource couldn't read MovedFromAttribute's internal data.");

            var dataType = data.GetType();
            var nameSpaceField = dataType.GetField("nameSpace", flags);
            var assemblyField = dataType.GetField("assembly", flags);
            var classNameField = dataType.GetField("className", flags);
            if (nameSpaceField == null || assemblyField == null || classNameField == null)
                throw new InvalidOperationException("ReadSource couldn't read MovedFromAttributeData's fields.");

            return ((string)nameSpaceField.GetValue(data),
                (string)assemblyField.GetValue(data),
                (string)classNameField.GetValue(data));
        }
    }
}
