# This workflow was adapted from com.unity.memoryprofiler

name: Format
on: pull_request

jobs:
  check:
    runs-on: unity-linux-runner
    strategy:
      matrix:
        project: [glTFast-Test, glTFast-Test-BuiltIn, glTFast-Test-entities, glTFast-Test-HDRP, glTFast-Test-minimalistic]
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run dotnet format
        id: format
        uses: ./.github/workflows/dotnet-format/
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          # A license key is not currently needed as that's handled via upm-ci. Consider speeding up this process by providing a Unity ID login instead and foregoing the need for npm, virtual x and upm-ci.
          #unityLicenseKey: ${{ secrets.UNITY_LICENSE }}
          project: ${{ matrix.project }}
          onlyFilesModifiedInPullRequest: true
          workingDirectory: '.'
          gitBranch: ${{ github.event.pull_request.head.ref }}
          alsoFormatWhitespace: true
          # Don't use xLTS version to avoid license issues
          unityVersion: "6000.0.75f1"
